# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W621MZ2v5t4os92F77OVmDsYnuN-0xQ-
"""

import datetime
import csv

# Pizza tabanları ve fiyatları
pizza_bases = {
    "Klasik": 10,
    "Margarita": 12,
    "TürkPizza": 14,
    "Sade Pizza":16
}

# Pizza malzemeleri ve fiyatları
pizza_toppings = {
    "Zeytin": 2,
    "Mantarlar": 1,
    "Keçi Peyniri": 1,
    "Et": 2,
    "Soğan": 2,
    "Mısır": 1
}

# Total hesabı hesaplayan fonksiyon
def calculate_cost(bases, toppings):
    cost = pizza_bases[bases]
    for topping in toppings:
        cost += pizza_toppings[topping]
    return cost

# Müşteri bilgileri için inputlar
name = input("İsminizi Giriniz: ")
address = input("Adresinizi Giriniz: ")
phone = input("Telefon Numaranızı Giriniz: ")

# Pizza için bilgiler
bases = input("Pizza tabanını seçiniz (Klasik, Margarita, TürkPizza, Sade Pizza): ")
toppings = input("Pizza malzemelerini seçiniz (virgülle ayırınız/Zeytin,Mantarlar,Keçi Peyniri,Et,Soğan,Mısır): ").split(",")

# Pizzanın tutarını hesaplanması
cost = calculate_cost(bases, toppings)

# Kredi kartı bilgileri
card_number = input("Kredi Kartı Numaranızı Giriniz: ")
expiration_date = input("Kredi Kartınızın Son Kullanım Tarihini Girinniz (AA/YY)? ")
security_code = input("Kredi Kartınızın Güvenlik Kodunu Giriniz: ")

# Güncel zaman ve tarih bilgisi
now = datetime.datetime.now()

# Sipariş, müşteri, kredi kartı ve zaman bilgilerinin bir csv dosyasına kaydedilmesi
with open("orders.csv", "a") as file:
    file.write(f"{now.strftime('%Y-%m-%d %H:%M:%S')},{name},{address},{phone},{bases},{','.join(toppings)},{cost},{card_number},{expiration_date},{security_code}\n")

print(f"Siparişiniz için teşekkür ederiz, {name}! Hesabınız ${cost}.")